const routes = {
    login : '/login',
    register : "/register",
    home :"/",
    userdetail:"/user",
    UserProfile :"/usersetting",
    categoryMovie : "/category/:id/show-movies",
    categoryTvSeries : "/category/:id/show-tvseries",
    movie : "/movie",
    addMovie : "/add-movie",
    watchMovie : "/watch-movie/:name",
    watchTvShow : "/watch-tvshow/:id",
    error404: "/error404",
    tvSeries : "/tvSeries",
    movieDetail : "/movie-detail/:name",
    test :"/dashBoard",
    favoriteMovies : "/favorite-movies",
    favoriteTvSeries : "/favorite-tvseries",
    search : "/search",
    registerVip : "/register-membership",
    bank : "/payment/",
    error401: "/error401",
    tvSeriesDetail : "/tvseries-detail/:name",
}
export default routes;