const routes = {
    login : '/login',
    register : "/register",
    home :"/",
    userdetail:"/user",
    UserProfile :"/usersetting",
    categoryMovie : "/category/:id/show-movies",
    categoryTvSeries : "/category/:id/show-tvseries",
    movie : "/movie",
    addMovie : "/add-movie",
    watchMovie : "/watch-movie/:name",
    watchTvShow : "/watch-tvshow/:name/:season_episode",
    error404: "/error404",
    tvSeries : "/tvSeries",
    movieDetail : "/movie-detail/:name",
    favoriteMovies : "/favorite-movies",
    favoriteTvSeries : "/favorite-tvseries",
    search : "/search",
}
export default routes;